"""Generates src/build_info.h with a build counter and the current git hash.

Run automatically by PlatformIO as a pre-script (see platformio.ini).
"""

import os
import subprocess

Import("env")  # noqa: F821  (injected by PlatformIO)

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
COUNTER_FILE = os.path.join(PROJECT_DIR, "build_number.txt")
HEADER_FILE = os.path.join(PROJECT_DIR, "src", "build_info.h")


def read_counter():
    try:
        with open(COUNTER_FILE, "r", encoding="utf-8") as handle:
            return int(handle.read().strip())
    except (OSError, ValueError):
        return 0


def git_hash():
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_DIR,
            stderr=subprocess.DEVNULL,
        )
        return out.decode("utf-8").strip()
    except (OSError, subprocess.CalledProcessError):
        return "nogit"


number = read_counter() + 1

with open(COUNTER_FILE, "w", encoding="utf-8") as handle:
    handle.write(str(number))

with open(HEADER_FILE, "w", encoding="utf-8") as handle:
    handle.write("// Generated by scripts/version_bump.py - do not edit.\n")
    handle.write("#pragma once\n")
    handle.write('#define BUILD_NUMBER %d\n' % number)
    handle.write('#define BUILD_GIT "%s"\n' % git_hash())

print("Build %d (%s)" % (number, git_hash()))
